[sssd]
services = nss, pam
domains = rebel-testing

[domain/corporate]
id_provider = idp
idp_type = keycloak:https://auth.machine-built.de/realms/rebel-testing/
idp_client_id = schloss-sssd
idp_client_secret = e9WkqoJl97NT6fOdRfiEWlAhcILrmoYwVM6dcJquiV9mXFpM5xj2z5nVs31dGc2SwVZAnbj4HgmfcURZpauTGC
idp_token_endpoint = https://auth.machine-built.de/realms/rebel-testing/protocol/openid-connect/token
idp_userinfo_endpoint = https://auth.machine-built.de/realms/rebel-testing/protocol/openid-connect/userinfo
idp_device_auth_endpoint = https://auth.machine-built.de/realms/rebel-testing/protocol/openid-connect/auth/device
idp_id_scope = profile
idp_auth_scope = openid profile email
auto_private_groups = true
use_fully_qualified_names = true

[nss]
default_shell = /bin/bash
fallback_homedir = /home/%f
